name: Build & Deploy on LAN Windows Server

# Trigger on pushes to your main branch (or change to your branch)
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    # This tells Actions to use any self-hosted Windows runner
    runs-on: [ self-hosted, windows ]

    steps:
      - uses: actions/checkout@v3

      - name: Publish .NET app
        run: dotnet publish D:/CodeToCheck/CICD/TaskManagement/ManagementSystem.WSAPI/ManagementSystem.WSAPI/ManagementSystem.WSAPI.csproj -c Release -o ./publish/CICD

      - name: Build Docker image from published output
        shell: powershell
        run: |
          docker build -t my-app:latest .

      - name: Stop & remove old container
        shell: powershell
        run: |
          docker stop my-app -ErrorAction SilentlyContinue
          docker rm   my-app -ErrorAction SilentlyContinue

      - name: Run new container
        shell: pwsh
        run: docker run -d --name my-app -p 9000:9000 my-app:latest
